import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/toast";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Rolezando  App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToastProvider>
          <div className="flex flex-col h-screen">
            <div className="h-[94px]">
              <Header />
            </div>
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
